apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ylv3rus7q-python-gitops
  description: This is GitOps manifest for ylv3rus7q-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ylv3rus7q-python
    backstage.io/kubernetes-id: ylv3rus7q-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ylv3rus7q-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ylv3rus7q-python
